language: go
go:
- 1.7.1
env:
  global:
  - SSH_KEY="travis_key"
  - GIT_NAME="David Shorter"
  - GIT_EMAIL="shorter.david@gmail.com"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="source"
before_install:
   - openssl aes-256-cbc -K $encrypted_e1bda4f7cbde_key -iv $encrypted_e1bda4f7cbde_iv -in travis_key.enc -out travis_key -d
before_script:
- go get -u -v github.com/kardianos/govendor
- go get -u -v github.com/spf13/hugo
- cd $GOPATH/src/github.com/spf13/hugo && govendor sync && go install
script:
- cd $HOME/gopath/src/github.com/TwosCompany/TwosCompany.github.io && hugo
- chmod a+x $HOME/gopath/src/github.com/TwosCompany/TwosCompany.github.io/scripts/deploy.sh
- "$HOME/gopath/src/github.com/TwosCompany/TwosCompany.github.io/scripts/deploy.sh"
