baseurl = "//twoscompany.github.io/"
languageCode = "en-us"
title = "Dating Service Auckland | Dating Agency | Introduction Agency"
[params]
    header = "Two's Company Ltd"
    description = "Introducing Single People since 2003"

[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:sasha@twoscompany.co.nz"
[[params.social]]
    title = "phone"
    icon = "phone"
    url = "callto:0800021522"
[[params.social]]
    title = "mobile"
    icon = "phone"
    url = "tel:021522922"
[[params.social]]
    title = "linkedin"
    icon = "linkedin"
    url = "http://linkedin.com/yourusername"
[[params.social]]
    title = "twitter"
    icon = "twitter"
    url = "http://twitter.com/yourusername"
[[params.social]]
    title = "facebook"
    icon = "facebook"
    url = "http://facebook.com/yourusername"